import { describe, expect, it } from 'vitest';
import type { CaptionTrack } from './types';
import {
    buildTranscriptUrl,
    extractCaptionTracks,
    formatTranscriptTimestamp,
    getPlayabilityError,
    parseJson3Transcript,
    sortCaptionTracks,
    transcriptUsesHours,
} from './transcript';

// Trimmed from a real InnerTube player response (video dQw4w9WgXcQ)
const PLAYER_RESPONSE = {
    playabilityStatus: { status: 'OK' },
    captions: {
        playerCaptionsTracklistRenderer: {
            captionTracks: [
                {
                    baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en&fmt=srv3',
                    name: { runs: [{ text: 'English' }] },
                    vssId: '.en',
                    languageCode: 'en',
                },
                {
                    baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&kind=asr&lang=en&fmt=srv3',
                    name: { runs: [{ text: 'English (auto-generated)' }] },
                    vssId: 'a.en',
                    languageCode: 'en',
                    kind: 'asr',
                },
                {
                    baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=de-DE&fmt=srv3',
                    name: { simpleText: 'German (Germany)' },
                    vssId: '.de-DE',
                    languageCode: 'de-DE',
                },
            ],
            audioTracks: [
                {
                    captionTrackIndices: [0, 2, 1],
                    defaultCaptionTrackIndex: 0,
                    hasDefaultTrack: true,
                },
            ],
            defaultAudioTrackIndex: 0,
        },
    },
};

// Trimmed from a real ASR json3 track: a no-seg window event, an aAppend
// newline filler, a multi-seg word stream, and a single-seg event.
const ASR_JSON3 = {
    events: [
        { tStartMs: 0, dDurationMs: 211879, id: 1, wpWinPosId: 1 },
        { tStartMs: 320, dDurationMs: 14260, wWinId: 1, segs: [{ utf8: '[Music]' }] },
        { tStartMs: 18790, wWinId: 1, aAppend: 1, segs: [{ utf8: '\n' }] },
        {
            tStartMs: 18800,
            dDurationMs: 7160,
            wWinId: 1,
            segs: [
                { utf8: "We're", acAsrConf: 0 },
                { utf8: ' no', tOffsetMs: 239, acAsrConf: 0 },
                { utf8: ' strangers', tOffsetMs: 559, acAsrConf: 0 },
                { utf8: ' to', tOffsetMs: 1040, acAsrConf: 0 },
            ],
        },
        { tStartMs: 22640, dDurationMs: 4320, segs: [{ utf8: '♪ You know the rules\nand so do I ♪' }] },
        { tStartMs: 25000, dDurationMs: 1000, segs: [{ utf8: '   ' }] },
        { tStartMs: 27040, dDurationMs: 4000, segs: [{ utf8: 'Tom &amp; Jerry' }] },
    ],
};

describe('getPlayabilityError', () => {
    it('returns null when the video is playable', () => {
        expect(getPlayabilityError(PLAYER_RESPONSE)).toBeNull();
    });

    it('returns the reason when present', () => {
        const response = { playabilityStatus: { status: 'ERROR', reason: 'Video unavailable' } };
        expect(getPlayabilityError(response)).toBe('Video unavailable');
    });

    it('returns a generic message when no reason is present', () => {
        const response = { playabilityStatus: { status: 'LOGIN_REQUIRED' } };
        expect(getPlayabilityError(response)).toBe('Video is not playable (LOGIN_REQUIRED)');
    });

    it('tolerates garbage input', () => {
        expect(getPlayabilityError(null)).toBeTruthy();
        expect(getPlayabilityError('junk')).toBeTruthy();
        expect(getPlayabilityError({})).toBeTruthy();
    });
});

describe('extractCaptionTracks', () => {
    it('extracts track metadata from a player response', () => {
        const tracks = extractCaptionTracks(PLAYER_RESPONSE);

        expect(tracks).toHaveLength(3);

        // Name from runs
        expect(tracks[0].name).toBe('English');
        expect(tracks[0].languageCode).toBe('en');
        expect(tracks[0].isAutoGenerated).toBe(false);
        expect(tracks[0].isDefault).toBe(true);

        // ASR track
        expect(tracks[1].name).toBe('English (auto-generated)');
        expect(tracks[1].isAutoGenerated).toBe(true);
        expect(tracks[1].isDefault).toBe(false);

        // Name from simpleText
        expect(tracks[2].name).toBe('German (Germany)');
        expect(tracks[2].languageCode).toBe('de-DE');
        expect(tracks[2].isDefault).toBe(false);
    });

    it('marks no track as default when the audio track info is missing', () => {
        const response = {
            captions: {
                playerCaptionsTracklistRenderer: {
                    captionTracks: [
                        {
                            baseUrl: 'https://www.youtube.com/api/timedtext?v=x&lang=en',
                            name: { simpleText: 'English' },
                            languageCode: 'en',
                        },
                    ],
                },
            },
        };
        const tracks = extractCaptionTracks(response);
        expect(tracks).toHaveLength(1);
        expect(tracks[0].isDefault).toBe(false);
    });

    it('returns [] when the response has no captions', () => {
        expect(extractCaptionTracks({ playabilityStatus: { status: 'OK' } })).toEqual([]);
        expect(extractCaptionTracks(null)).toEqual([]);
    });
});

describe('sortCaptionTracks', () => {
    it('orders default first, then manual, then auto-generated', () => {
        const tracks: CaptionTrack[] = [
            { baseUrl: 'asr', languageCode: 'en', name: 'English (auto-generated)', isAutoGenerated: true, isDefault: false },
            { baseUrl: 'de', languageCode: 'de', name: 'German', isAutoGenerated: false, isDefault: false },
            { baseUrl: 'en', languageCode: 'en', name: 'English', isAutoGenerated: false, isDefault: true },
            { baseUrl: 'ja', languageCode: 'ja', name: 'Japanese', isAutoGenerated: false, isDefault: false },
        ];

        const sorted = sortCaptionTracks(tracks);
        expect(sorted.map(t => t.baseUrl)).toEqual(['en', 'de', 'ja', 'asr']);
        // Original array untouched
        expect(tracks[0].baseUrl).toBe('asr');
    });
});

describe('buildTranscriptUrl', () => {
    it('replaces an existing fmt param with json3', () => {
        const url = buildTranscriptUrl('https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en&fmt=srv3');
        const parsed = new URL(url);
        expect(parsed.searchParams.get('fmt')).toBe('json3');
        expect(url).not.toContain('fmt=srv3');
        expect(parsed.searchParams.get('lang')).toBe('en');
    });

    it('adds fmt=json3 when no fmt param exists', () => {
        const url = buildTranscriptUrl('https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en');
        expect(new URL(url).searchParams.get('fmt')).toBe('json3');
    });
});

describe('parseJson3Transcript', () => {
    it('joins segs, collapses whitespace, skips filler events, decodes entities', () => {
        const entries = parseJson3Transcript(ASR_JSON3);

        expect(entries).toEqual([
            { timestampSec: 0, text: '[Music]' },
            { timestampSec: 18, text: "We're no strangers to" },
            { timestampSec: 22, text: '♪ You know the rules and so do I ♪' },
            { timestampSec: 27, text: 'Tom & Jerry' },
        ]);
    });

    it('floors millisecond timestamps to seconds', () => {
        const entries = parseJson3Transcript({
            events: [{ tStartMs: 65999, segs: [{ utf8: 'late' }] }],
        });
        expect(entries[0].timestampSec).toBe(65);
    });

    it('returns [] for invalid input', () => {
        expect(parseJson3Transcript(null)).toEqual([]);
        expect(parseJson3Transcript('junk')).toEqual([]);
        expect(parseJson3Transcript({})).toEqual([]);
        expect(parseJson3Transcript({ events: 'nope' })).toEqual([]);
    });
});

describe('formatTranscriptTimestamp', () => {
    it('formats m:ss when not using hours', () => {
        expect(formatTranscriptTimestamp(5, false)).toBe('0:05');
        expect(formatTranscriptTimestamp(115, false)).toBe('1:55');
    });

    it('formats h:mm:ss when using hours', () => {
        expect(formatTranscriptTimestamp(3725, true)).toBe('1:02:05');
        expect(formatTranscriptTimestamp(5, true)).toBe('0:00:05');
    });
});

describe('transcriptUsesHours', () => {
    it('is true when the video duration is an hour or more', () => {
        expect(transcriptUsesHours([], 3600)).toBe(true);
        expect(transcriptUsesHours([{ timestampSec: 5, text: 'x' }], 4000)).toBe(true);
    });

    it('is true when the last caption reaches an hour or more', () => {
        expect(transcriptUsesHours([{ timestampSec: 3700, text: 'x' }], 0)).toBe(true);
    });

    it('is false for short videos and transcripts', () => {
        expect(transcriptUsesHours([{ timestampSec: 100, text: 'x' }], 300)).toBe(false);
        expect(transcriptUsesHours([], 0)).toBe(false);
    });
});
