import { describe, expect, it } from 'vitest';
import type { CaptionTrack, TranscriptEntry } from './types';
import {
    buildTranscriptUrl,
    extractCaptionTracks,
    findActiveCaptionIndex,
    formatCaptionFileTimestamp,
    formatTranscriptTimestamp,
    getPlayabilityError,
    parseCaptionFileTimestamp,
    parseJson3Transcript,
    sortCaptionTracks,
    transcriptUsesHours,
} from './transcript';

// Trimmed from a real InnerTube player response (video dQw4w9WgXcQ)
const PLAYER_RESPONSE = {
    playabilityStatus: { status: 'OK' },
    captions: {
        playerCaptionsTracklistRenderer: {
            captionTracks: [
                {
                    baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en&fmt=srv3',
                    name: { runs: [{ text: 'English' }] },
                    vssId: '.en',
                    languageCode: 'en',
                },
                {
                    baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&kind=asr&lang=en&fmt=srv3',
                    name: { runs: [{ text: 'English (auto-generated)' }] },
                    vssId: 'a.en',
                    languageCode: 'en',
                    kind: 'asr',
                },
                {
                    baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=de-DE&fmt=srv3',
                    name: { simpleText: 'German (Germany)' },
                    vssId: '.de-DE',
                    languageCode: 'de-DE',
                },
            ],
            audioTracks: [
                {
                    captionTrackIndices: [0, 2, 1],
                    defaultCaptionTrackIndex: 0,
                    hasDefaultTrack: true,
                },
            ],
            defaultAudioTrackIndex: 0,
        },
    },
};

// Trimmed from a real ASR json3 track: a no-seg window event, an aAppend
// newline filler, a multi-seg word stream, and a single-seg event.
const ASR_JSON3 = {
    events: [
        { tStartMs: 0, dDurationMs: 211879, id: 1, wpWinPosId: 1 },
        { tStartMs: 320, dDurationMs: 14260, wWinId: 1, segs: [{ utf8: '[Music]' }] },
        { tStartMs: 18790, wWinId: 1, aAppend: 1, segs: [{ utf8: '\n' }] },
        {
            tStartMs: 18800,
            dDurationMs: 7160,
            wWinId: 1,
            segs: [
                { utf8: "We're", acAsrConf: 0 },
                { utf8: ' no', tOffsetMs: 239, acAsrConf: 0 },
                { utf8: ' strangers', tOffsetMs: 559, acAsrConf: 0 },
                { utf8: ' to', tOffsetMs: 1040, acAsrConf: 0 },
            ],
        },
        { tStartMs: 22640, dDurationMs: 4320, segs: [{ utf8: '♪ You know the rules\nand so do I ♪' }] },
        { tStartMs: 25000, dDurationMs: 1000, segs: [{ utf8: '   ' }] },
        { tStartMs: 27040, dDurationMs: 4000, segs: [{ utf8: 'Tom &amp; Jerry' }] },
    ],
};

describe('getPlayabilityError', () => {
    it('returns null when the video is playable', () => {
        expect(getPlayabilityError(PLAYER_RESPONSE)).toBeNull();
    });

    it('returns the reason when present', () => {
        const response = { playabilityStatus: { status: 'ERROR', reason: 'Video unavailable' } };
        expect(getPlayabilityError(response)).toBe('Video unavailable');
    });

    it('returns a generic message when no reason is present', () => {
        const response = { playabilityStatus: { status: 'LOGIN_REQUIRED' } };
        expect(getPlayabilityError(response)).toBe('Video is not playable (LOGIN_REQUIRED)');
    });

    it('tolerates garbage input', () => {
        expect(getPlayabilityError(null)).toBeTruthy();
        expect(getPlayabilityError('junk')).toBeTruthy();
        expect(getPlayabilityError({})).toBeTruthy();
    });
});

describe('extractCaptionTracks', () => {
    it('extracts track metadata from a player response', () => {
        const tracks = extractCaptionTracks(PLAYER_RESPONSE);

        expect(tracks).toHaveLength(3);

        // Name from runs
        expect(tracks[0].name).toBe('English');
        expect(tracks[0].languageCode).toBe('en');
        expect(tracks[0].isAutoGenerated).toBe(false);
        expect(tracks[0].isDefault).toBe(true);

        // ASR track
        expect(tracks[1].name).toBe('English (auto-generated)');
        expect(tracks[1].isAutoGenerated).toBe(true);
        expect(tracks[1].isDefault).toBe(false);

        // Name from simpleText
        expect(tracks[2].name).toBe('German (Germany)');
        expect(tracks[2].languageCode).toBe('de-DE');
        expect(tracks[2].isDefault).toBe(false);
    });

    it('marks no track as default when the audio track info is missing', () => {
        const response = {
            captions: {
                playerCaptionsTracklistRenderer: {
                    captionTracks: [
                        {
                            baseUrl: 'https://www.youtube.com/api/timedtext?v=x&lang=en',
                            name: { simpleText: 'English' },
                            languageCode: 'en',
                        },
                    ],
                },
            },
        };
        const tracks = extractCaptionTracks(response);
        expect(tracks).toHaveLength(1);
        expect(tracks[0].isDefault).toBe(false);
    });

    it('returns [] when the response has no captions', () => {
        expect(extractCaptionTracks({ playabilityStatus: { status: 'OK' } })).toEqual([]);
        expect(extractCaptionTracks(null)).toEqual([]);
    });
});

describe('sortCaptionTracks', () => {
    it('orders default first, then manual, then auto-generated', () => {
        const tracks: CaptionTrack[] = [
            { baseUrl: 'asr', languageCode: 'en', name: 'English (auto-generated)', isAutoGenerated: true, isDefault: false },
            { baseUrl: 'de', languageCode: 'de', name: 'German', isAutoGenerated: false, isDefault: false },
            { baseUrl: 'en', languageCode: 'en', name: 'English', isAutoGenerated: false, isDefault: true },
            { baseUrl: 'ja', languageCode: 'ja', name: 'Japanese', isAutoGenerated: false, isDefault: false },
        ];

        const sorted = sortCaptionTracks(tracks);
        expect(sorted.map(t => t.baseUrl)).toEqual(['en', 'de', 'ja', 'asr']);
        // Original array untouched
        expect(tracks[0].baseUrl).toBe('asr');
    });
});

describe('buildTranscriptUrl', () => {
    it('replaces an existing fmt param with json3', () => {
        const url = buildTranscriptUrl('https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en&fmt=srv3');
        const parsed = new URL(url);
        expect(parsed.searchParams.get('fmt')).toBe('json3');
        expect(url).not.toContain('fmt=srv3');
        expect(parsed.searchParams.get('lang')).toBe('en');
    });

    it('adds fmt=json3 when no fmt param exists', () => {
        const url = buildTranscriptUrl('https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en');
        expect(new URL(url).searchParams.get('fmt')).toBe('json3');
    });
});

describe('parseJson3Transcript', () => {
    it('joins segs, collapses whitespace, skips filler events, decodes entities', () => {
        const entries = parseJson3Transcript(ASR_JSON3);

        expect(entries).toEqual([
            { startMs: 320, durationMs: 14260, text: '[Music]' },
            { startMs: 18800, durationMs: 7160, text: "We're no strangers to" },
            { startMs: 22640, durationMs: 4320, text: '♪ You know the rules and so do I ♪' },
            { startMs: 27040, durationMs: 4000, text: 'Tom & Jerry' },
        ]);
    });

    it('preserves exact start and duration milliseconds', () => {
        const entries = parseJson3Transcript({
            events: [{ tStartMs: 65999.4, dDurationMs: 1234.6, segs: [{ utf8: 'late' }] }],
        });
        expect(entries[0]).toEqual({ startMs: 65999, durationMs: 1235, text: 'late' });
    });

    it('omits durationMs when absent or non-positive', () => {
        const entries = parseJson3Transcript({
            events: [
                { tStartMs: 100, segs: [{ utf8: 'a' }] },
                { tStartMs: 200, dDurationMs: 0, segs: [{ utf8: 'b' }] },
                { tStartMs: 300, dDurationMs: -50, segs: [{ utf8: 'c' }] },
                { tStartMs: 400, dDurationMs: 0.4, segs: [{ utf8: 'd' }] },
            ],
        });
        expect(entries).toEqual([
            { startMs: 100, text: 'a' },
            { startMs: 200, text: 'b' },
            { startMs: 300, text: 'c' },
            { startMs: 400, text: 'd' },
        ]);
        expect(entries[0]).not.toHaveProperty('durationMs');
        expect(entries[3]).not.toHaveProperty('durationMs');
    });

    it('returns [] for invalid input', () => {
        expect(parseJson3Transcript(null)).toEqual([]);
        expect(parseJson3Transcript('junk')).toEqual([]);
        expect(parseJson3Transcript({})).toEqual([]);
        expect(parseJson3Transcript({ events: 'nope' })).toEqual([]);
    });
});

describe('formatTranscriptTimestamp', () => {
    it('formats m:ss when not using hours', () => {
        expect(formatTranscriptTimestamp(5000, false)).toBe('0:05');
        expect(formatTranscriptTimestamp(115125, false)).toBe('1:55');
    });

    it('formats h:mm:ss when using hours', () => {
        expect(formatTranscriptTimestamp(3725125, true)).toBe('1:02:05');
        expect(formatTranscriptTimestamp(5000, true)).toBe('0:00:05');
    });
});

describe('formatCaptionFileTimestamp', () => {
    it('uses the compact clock style for whole-second values', () => {
        expect(formatCaptionFileTimestamp(5000)).toBe('5');
        expect(formatCaptionFileTimestamp(115000)).toBe('1:55');
        expect(formatCaptionFileTimestamp(3725000)).toBe('1:02:05');
    });

    it('emits .mmm for fractional values', () => {
        expect(formatCaptionFileTimestamp(320)).toBe('0:00.320');
        expect(formatCaptionFileTimestamp(18800)).toBe('0:18.800');
        expect(formatCaptionFileTimestamp(115125)).toBe('1:55.125');
        expect(formatCaptionFileTimestamp(3725125)).toBe('1:02:05.125');
    });
});

describe('parseCaptionFileTimestamp', () => {
    it('parses seconds, m:ss and h:mm:ss with optional milliseconds', () => {
        expect(parseCaptionFileTimestamp('5')).toBe(5000);
        expect(parseCaptionFileTimestamp('1:55')).toBe(115000);
        expect(parseCaptionFileTimestamp('1:02:05')).toBe(3725000);
        expect(parseCaptionFileTimestamp('0:00.320')).toBe(320);
        expect(parseCaptionFileTimestamp('0:18.8')).toBe(18800);
        expect(parseCaptionFileTimestamp('1:55.125')).toBe(115125);
        expect(parseCaptionFileTimestamp('1:02:05.005')).toBe(3725005);
    });

    it('rejects invalid minute/second ranges, malformed fractions, and garbage', () => {
        expect(parseCaptionFileTimestamp('1:60')).toBeNull();
        expect(parseCaptionFileTimestamp('1:62:00')).toBeNull();
        expect(parseCaptionFileTimestamp('5.1234')).toBeNull();
        expect(parseCaptionFileTimestamp('5.')).toBeNull();
        expect(parseCaptionFileTimestamp('abc')).toBeNull();
        expect(parseCaptionFileTimestamp('-5')).toBeNull();
        expect(parseCaptionFileTimestamp('')).toBeNull();
    });
});

describe('findActiveCaptionIndex', () => {
    const CAPTIONS: TranscriptEntry[] = [
        { startMs: 1000, durationMs: 2000, text: 'a' },
        { startMs: 4000, durationMs: 2000, text: 'b' },
        { startMs: 8000, text: 'c' },
        { startMs: 12000, text: 'd' },
    ];

    it('returns null before the first caption', () => {
        expect(findActiveCaptionIndex(CAPTIONS, 500)).toBeNull();
        expect(findActiveCaptionIndex([], 1000)).toBeNull();
    });

    it('activates a caption at its exact start and during its duration', () => {
        expect(findActiveCaptionIndex(CAPTIONS, 1000)).toBe(0);
        expect(findActiveCaptionIndex(CAPTIONS, 2500)).toBe(0);
    });

    it('returns null at an exact end boundary and inside gaps', () => {
        expect(findActiveCaptionIndex(CAPTIONS, 3000)).toBeNull();
        expect(findActiveCaptionIndex(CAPTIONS, 3500)).toBeNull();
        expect(findActiveCaptionIndex(CAPTIONS, 7000)).toBeNull();
    });

    it('activates a timed caption when another caption starts at its end', () => {
        const contiguous: TranscriptEntry[] = [
            { startMs: 1000, durationMs: 1000, text: 'a' },
            { startMs: 2000, durationMs: 1000, text: 'b' },
        ];
        expect(findActiveCaptionIndex(contiguous, 2000)).toBe(1);
    });

    it('keeps a caption without duration active until the next start', () => {
        expect(findActiveCaptionIndex(CAPTIONS, 9000)).toBe(2);
        expect(findActiveCaptionIndex(CAPTIONS, 11999)).toBe(2);
        expect(findActiveCaptionIndex(CAPTIONS, 12000)).toBe(3);
    });

    it('keeps the final no-duration caption active', () => {
        expect(findActiveCaptionIndex(CAPTIONS, 999999)).toBe(3);
    });

    it('resolves duplicate start times to the last one', () => {
        const dupes: TranscriptEntry[] = [
            { startMs: 1000, text: 'first' },
            { startMs: 1000, text: 'second' },
            { startMs: 2000, text: 'third' },
        ];
        expect(findActiveCaptionIndex(dupes, 1000)).toBe(1);
        expect(findActiveCaptionIndex(dupes, 1500)).toBe(1);
    });
});

describe('transcriptUsesHours', () => {
    it('is true when the video duration is an hour or more', () => {
        expect(transcriptUsesHours([], 3600)).toBe(true);
        expect(transcriptUsesHours([{ startMs: 5000, text: 'x' }], 4000)).toBe(true);
    });

    it('is true when the last caption reaches an hour or more', () => {
        expect(transcriptUsesHours([{ startMs: 3_700_000, text: 'x' }], 0)).toBe(true);
    });

    it('is false for short videos and transcripts', () => {
        expect(transcriptUsesHours([{ startMs: 100_000, text: 'x' }], 300)).toBe(false);
        expect(transcriptUsesHours([], 0)).toBe(false);
    });
});
