import { CaptionTrack, TranscriptEntry } from './types';

function isRecord(value: unknown): value is Record<string, unknown> {
    return value !== null && typeof value === 'object';
}

/**
 * Returns a user-readable error when the player response is not playable,
 * or null when playabilityStatus.status is 'OK'.
 */
export function getPlayabilityError(playerResponse: unknown): string | null {
    if (!isRecord(playerResponse) || !isRecord(playerResponse.playabilityStatus)) {
        return 'Unexpected response from YouTube.';
    }

    const { status, reason } = playerResponse.playabilityStatus;
    if (status === 'OK') {
        return null;
    }
    if (typeof reason === 'string' && reason) {
        return reason;
    }
    return `Video is not playable (${typeof status === 'string' ? status : 'unknown'})`;
}

function extractTrackName(name: unknown, fallback: string): string {
    if (!isRecord(name)) {
        return fallback;
    }
    if (typeof name.simpleText === 'string' && name.simpleText) {
        return name.simpleText;
    }
    if (Array.isArray(name.runs)) {
        const joined = name.runs
            .map(run => (isRecord(run) && typeof run.text === 'string' ? run.text : ''))
            .join('');
        if (joined) {
            return joined;
        }
    }
    return fallback;
}

/**
 * Extracts the caption tracks from an InnerTube player response.
 * The default track is the one referenced by the default audio track's
 * defaultCaptionTrackIndex.
 */
export function extractCaptionTracks(playerResponse: unknown): CaptionTrack[] {
    if (!isRecord(playerResponse) || !isRecord(playerResponse.captions)) {
        return [];
    }
    const renderer = playerResponse.captions.playerCaptionsTracklistRenderer;
    if (!isRecord(renderer) || !Array.isArray(renderer.captionTracks)) {
        return [];
    }

    const captionTracks: unknown[] = renderer.captionTracks;
    const audioTracks: unknown[] = Array.isArray(renderer.audioTracks) ? renderer.audioTracks : [];
    const defaultAudioTrackIndex = typeof renderer.defaultAudioTrackIndex === 'number'
        ? renderer.defaultAudioTrackIndex
        : 0;
    const defaultAudioTrack = audioTracks[defaultAudioTrackIndex];
    const defaultCaptionTrackIndex = isRecord(defaultAudioTrack) && typeof defaultAudioTrack.defaultCaptionTrackIndex === 'number'
        ? defaultAudioTrack.defaultCaptionTrackIndex
        : null;

    const tracks: CaptionTrack[] = [];
    for (let i = 0; i < captionTracks.length; i++) {
        const raw = captionTracks[i];
        if (!isRecord(raw) || typeof raw.baseUrl !== 'string') {
            continue;
        }
        const languageCode = typeof raw.languageCode === 'string' ? raw.languageCode : '';
        tracks.push({
            baseUrl: raw.baseUrl,
            languageCode,
            name: extractTrackName(raw.name, languageCode),
            isAutoGenerated: raw.kind === 'asr',
            isDefault: defaultCaptionTrackIndex !== null && i === defaultCaptionTrackIndex,
        });
    }
    return tracks;
}

/** Orders tracks: default first, then manual tracks, then auto-generated. */
export function sortCaptionTracks(tracks: CaptionTrack[]): CaptionTrack[] {
    const rank = (track: CaptionTrack): number => {
        if (track.isDefault) return 0;
        return track.isAutoGenerated ? 2 : 1;
    };
    return [...tracks].sort((a, b) => rank(a) - rank(b));
}

/** Rewrites a timedtext baseUrl to request the json3 caption format. */
export function buildTranscriptUrl(baseUrl: string): string {
    const url = new URL(baseUrl);
    url.searchParams.delete('fmt');
    url.searchParams.set('fmt', 'json3');
    return url.toString();
}

function decodeEntities(text: string): string {
    return text
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&amp;/g, '&');
}

/**
 * Parses a json3 timedtext response into transcript entries.
 * Skips aAppend filler events, events without segs, and blank results.
 */
export function parseJson3Transcript(json: unknown): TranscriptEntry[] {
    if (!isRecord(json) || !Array.isArray(json.events)) {
        return [];
    }

    const entries: TranscriptEntry[] = [];
    for (const event of json.events) {
        if (!isRecord(event) || event.aAppend === 1 || !Array.isArray(event.segs)) {
            continue;
        }
        const rawText = event.segs
            .map(seg => (isRecord(seg) && typeof seg.utf8 === 'string' ? seg.utf8 : ''))
            .join('')
            .replace(/\s+/g, ' ')
            .trim();
        const text = decodeEntities(rawText);
        if (!text) {
            continue;
        }
        const startMs = typeof event.tStartMs === 'number' && Number.isFinite(event.tStartMs)
            ? Math.max(0, Math.round(event.tStartMs))
            : 0;
        const entry: TranscriptEntry = { startMs, text };
        if (typeof event.dDurationMs === 'number' && Number.isFinite(event.dDurationMs)) {
            const durationMs = Math.round(event.dDurationMs);
            if (durationMs > 0) {
                entry.durationMs = durationMs;
            }
        }
        entries.push(entry);
    }

    entries.sort((a, b) => a.startMs - b.startMs);
    return entries;
}

/** Formats a caption timestamp for display as m:ss, or h:mm:ss when useHours is set. */
export function formatTranscriptTimestamp(startMs: number, useHours: boolean): string {
    const totalSec = Math.floor(startMs / 1000);
    const h = Math.floor(totalSec / 3600);
    const m = Math.floor((totalSec % 3600) / 60);
    const s = totalSec % 60;
    const pad = (num: number) => num.toString().padStart(2, '0');
    if (useHours) {
        return `${h}:${pad(m)}:${pad(s)}`;
    }
    return `${m}:${pad(s)}`;
}

export function formatCaptionFileTimestamp(startMs: number): string {
    const totalMs = Math.max(0, Math.round(startMs));
    const ms = totalMs % 1000;
    const totalSec = Math.floor(totalMs / 1000);
    const h = Math.floor(totalSec / 3600);
    const m = Math.floor((totalSec % 3600) / 60);
    const s = totalSec % 60;
    const pad = (num: number) => num.toString().padStart(2, '0');

    if (ms !== 0) {
        const msStr = ms.toString().padStart(3, '0');
        if (h > 0) {
            return `${h}:${pad(m)}:${pad(s)}.${msStr}`;
        }
        return `${m}:${pad(s)}.${msStr}`;
    }

    if (h > 0) {
        return `${h}:${pad(m)}:${pad(s)}`;
    }
    if (m > 0) {
        return `${m}:${pad(s)}`;
    }
    return `${s}`;
}

export function parseCaptionFileTimestamp(value: string): number | null {
    const match = /^(\d+)(?::([0-5]\d):([0-5]\d)|:([0-5]\d))?(?:\.(\d{1,3}))?$/.exec(value.trim());
    if (!match) {
        return null;
    }

    const first = Number(match[1]);
    if (!Number.isFinite(first)) {
        return null;
    }

    let totalMs: number;
    if (match[2] !== undefined && match[3] !== undefined) {
        totalMs = (first * 3600 + Number(match[2]) * 60 + Number(match[3])) * 1000;
    } else if (match[4] !== undefined) {
        totalMs = (first * 60 + Number(match[4])) * 1000;
    } else {
        totalMs = first * 1000;
    }

    if (match[5] !== undefined) {
        totalMs += Number(match[5].padEnd(3, '0'));
    }

    return totalMs;
}

export function findActiveCaptionIndex(entries: TranscriptEntry[], currentTimeMs: number): number | null {
    let lo = 0;
    let hi = entries.length - 1;
    let candidate = -1;
    while (lo <= hi) {
        const mid = (lo + hi) >> 1;
        if (entries[mid].startMs <= currentTimeMs) {
            candidate = mid;
            lo = mid + 1;
        } else {
            hi = mid - 1;
        }
    }

    if (candidate === -1) {
        return null;
    }

    const entry = entries[candidate];
    if (entry.durationMs !== undefined && currentTimeMs >= entry.startMs + entry.durationMs) {
        return null;
    }

    return candidate;
}

/** Captions should use hour format when the video or the last caption reaches 1h+. */
export function transcriptUsesHours(entries: TranscriptEntry[], durationSec: number): boolean {
    if (durationSec >= 3600) {
        return true;
    }
    const last = entries[entries.length - 1];
    return last !== undefined && last.startMs >= 3_600_000;
}

