import { CaptionTrack, TranscriptEntry } from './types';

function isRecord(value: unknown): value is Record<string, unknown> {
    return value !== null && typeof value === 'object';
}

/**
 * Returns a user-readable error when the player response is not playable,
 * or null when playabilityStatus.status is 'OK'.
 */
export function getPlayabilityError(playerResponse: unknown): string | null {
    if (!isRecord(playerResponse) || !isRecord(playerResponse.playabilityStatus)) {
        return 'Unexpected response from YouTube.';
    }

    const { status, reason } = playerResponse.playabilityStatus;
    if (status === 'OK') {
        return null;
    }
    if (typeof reason === 'string' && reason) {
        return reason;
    }
    return `Video is not playable (${typeof status === 'string' ? status : 'unknown'})`;
}

function extractTrackName(name: unknown, fallback: string): string {
    if (!isRecord(name)) {
        return fallback;
    }
    if (typeof name.simpleText === 'string' && name.simpleText) {
        return name.simpleText;
    }
    if (Array.isArray(name.runs)) {
        const joined = name.runs
            .map(run => (isRecord(run) && typeof run.text === 'string' ? run.text : ''))
            .join('');
        if (joined) {
            return joined;
        }
    }
    return fallback;
}

/**
 * Extracts the caption tracks from an InnerTube player response.
 * The default track is the one referenced by the default audio track's
 * defaultCaptionTrackIndex.
 */
export function extractCaptionTracks(playerResponse: unknown): CaptionTrack[] {
    if (!isRecord(playerResponse) || !isRecord(playerResponse.captions)) {
        return [];
    }
    const renderer = playerResponse.captions.playerCaptionsTracklistRenderer;
    if (!isRecord(renderer) || !Array.isArray(renderer.captionTracks)) {
        return [];
    }

    const captionTracks: unknown[] = renderer.captionTracks;
    const audioTracks: unknown[] = Array.isArray(renderer.audioTracks) ? renderer.audioTracks : [];
    const defaultAudioTrackIndex = typeof renderer.defaultAudioTrackIndex === 'number'
        ? renderer.defaultAudioTrackIndex
        : 0;
    const defaultAudioTrack = audioTracks[defaultAudioTrackIndex];
    const defaultCaptionTrackIndex = isRecord(defaultAudioTrack) && typeof defaultAudioTrack.defaultCaptionTrackIndex === 'number'
        ? defaultAudioTrack.defaultCaptionTrackIndex
        : null;

    const tracks: CaptionTrack[] = [];
    for (let i = 0; i < captionTracks.length; i++) {
        const raw = captionTracks[i];
        if (!isRecord(raw) || typeof raw.baseUrl !== 'string') {
            continue;
        }
        const languageCode = typeof raw.languageCode === 'string' ? raw.languageCode : '';
        tracks.push({
            baseUrl: raw.baseUrl,
            languageCode,
            name: extractTrackName(raw.name, languageCode),
            isAutoGenerated: raw.kind === 'asr',
            isDefault: defaultCaptionTrackIndex !== null && i === defaultCaptionTrackIndex,
        });
    }
    return tracks;
}

/** Orders tracks: default first, then manual tracks, then auto-generated. */
export function sortCaptionTracks(tracks: CaptionTrack[]): CaptionTrack[] {
    const rank = (track: CaptionTrack): number => {
        if (track.isDefault) return 0;
        return track.isAutoGenerated ? 2 : 1;
    };
    return [...tracks].sort((a, b) => rank(a) - rank(b));
}

/** Rewrites a timedtext baseUrl to request the json3 caption format. */
export function buildTranscriptUrl(baseUrl: string): string {
    const url = new URL(baseUrl);
    url.searchParams.delete('fmt');
    url.searchParams.set('fmt', 'json3');
    return url.toString();
}

function decodeEntities(text: string): string {
    return text
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&amp;/g, '&');
}

/**
 * Parses a json3 timedtext response into transcript entries.
 * Skips aAppend filler events, events without segs, and blank results.
 */
export function parseJson3Transcript(json: unknown): TranscriptEntry[] {
    if (!isRecord(json) || !Array.isArray(json.events)) {
        return [];
    }

    const entries: TranscriptEntry[] = [];
    for (const event of json.events) {
        if (!isRecord(event) || event.aAppend === 1 || !Array.isArray(event.segs)) {
            continue;
        }
        const rawText = event.segs
            .map(seg => (isRecord(seg) && typeof seg.utf8 === 'string' ? seg.utf8 : ''))
            .join('')
            .replace(/\s+/g, ' ')
            .trim();
        const text = decodeEntities(rawText);
        if (!text) {
            continue;
        }
        const tStartMs = typeof event.tStartMs === 'number' ? event.tStartMs : 0;
        entries.push({ timestampSec: Math.floor(tStartMs / 1000), text });
    }

    entries.sort((a, b) => a.timestampSec - b.timestampSec);
    return entries;
}

/** Formats a caption timestamp as m:ss, or h:mm:ss when useHours is set. */
export function formatTranscriptTimestamp(sec: number, useHours: boolean): string {
    const h = Math.floor(sec / 3600);
    const m = Math.floor((sec % 3600) / 60);
    const s = Math.floor(sec % 60);
    const pad = (num: number) => num.toString().padStart(2, '0');
    if (useHours) {
        return `${h}:${pad(m)}:${pad(s)}`;
    }
    return `${m}:${pad(s)}`;
}

/** Captions should use hour format when the video or the last caption reaches 1h+. */
export function transcriptUsesHours(entries: TranscriptEntry[], durationSec: number): boolean {
    if (durationSec >= 3600) {
        return true;
    }
    const last = entries[entries.length - 1];
    return last !== undefined && last.timestampSec >= 3600;
}

